# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PresionArterial' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '12.4'
  # Pods for PresionArterial
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  use_frameworks!

  # Pods for PresionArterial
pod 'Charts'
pod 'Firebase/Auth'

end
